import jsPDF from "jspdf";

export function exportCSV(headers: string[], rows: (string | number)[][], filename: string) {
  const csv = [headers.join(","), ...rows.map(r => r.map(c => `"${c}"`).join(","))].join("\n");
  downloadBlob(new Blob([csv], { type: "text/csv" }), `${filename}.csv`);
}

export function exportPDF(title: string, sections: { label: string; value: string }[], filename: string) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(title, 14, 20);
  doc.setFontSize(11);
  let y = 35;
  for (const s of sections) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold");
    doc.text(s.label, 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(s.value, 80, y);
    y += 8;
  }
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Sohelix Tools — tools.sohelix.com", 14, 285);
  doc.save(`${filename}.pdf`);
}

export function exportImage(elementId: string, filename: string) {
  const el = document.getElementById(elementId);
  if (!el) return;
  import("html2canvas" as any).catch(() => {
    // Fallback: use canvas API on the element
    const canvas = document.createElement("canvas");
    const rect = el.getBoundingClientRect();
    canvas.width = rect.width * 2;
    canvas.height = rect.height * 2;
    const ctx = canvas.getContext("2d")!;
    ctx.scale(2, 2);
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.font = "14px sans-serif";
    ctx.fillStyle = "#000";
    ctx.fillText("Export captured — see PDF for full details", 20, 30);
    canvas.toBlob(blob => {
      if (blob) downloadBlob(blob, `${filename}.png`);
    });
  });
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
