import { useState } from "react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import FileUploadZone from "@/components/FileUploadZone";
import { Download } from "lucide-react";

const SIZES = [16, 32, 48, 64, 180];

const FaviconGeneratorTool = () => {
  const [previews, setPreviews] = useState<{ size: number; dataUrl: string }[]>([]);
  const [sourceFile, setSourceFile] = useState<File | null>(null);

  const generateFavicons = (file: File) => {
    setSourceFile(file);
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      const results: { size: number; dataUrl: string }[] = [];
      for (const size of SIZES) {
        const canvas = document.createElement("canvas");
        canvas.width = size;
        canvas.height = size;
        const ctx = canvas.getContext("2d")!;
        ctx.drawImage(img, 0, 0, size, size);
        results.push({ size, dataUrl: canvas.toDataURL("image/png") });
      }
      setPreviews(results);
    };
    img.onerror = () => toast({ title: "Error loading image", variant: "destructive" });
    img.src = objectUrl;
  };

  const handleFiles = (files: File[]) => {
    const file = files[0];
    if (!file || !file.type.startsWith("image/")) {
      toast({ title: "Please upload an image file", variant: "destructive" });
      return;
    }
    generateFavicons(file);
  };

  const downloadSingle = (preview: { size: number; dataUrl: string }) => {
    const a = document.createElement("a");
    a.href = preview.dataUrl;
    a.download = `favicon-${preview.size}x${preview.size}.png`;
    a.click();
  };

  const downloadAll = async () => {
    try {
      const JSZip = (await import("jszip")).default;
      const zip = new JSZip();
      for (const p of previews) {
        const res = await fetch(p.dataUrl);
        if (!res.ok) {
          console.warn("[FaviconGenerator] Failed to fetch favicon blob:", res.status, res.statusText);
          continue;
        }
        const contentType = res.headers.get("content-type") || "";
        if (contentType.includes("text/html")) {
          console.warn("[FaviconGenerator] Unexpected HTML response instead of image blob");
          continue;
        }
        const blob = await res.blob();
        zip.file(`favicon-${p.size}x${p.size}.png`, blob);
      }
      // Generate ICO-style note
      zip.file("README.txt", "Generated by Sohelix Tools\nSizes: " + SIZES.join(", ") + "px\n\nPlace these in your website root directory.");

      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = "favicons.zip";
      a.click();
      URL.revokeObjectURL(url);
      toast({ title: "Favicon package downloaded!" });
    } catch (err) {
      toast({ title: "Error creating ZIP", description: String(err), variant: "destructive" });
    }
  };

  return (
    <div className="space-y-5">
      <FileUploadZone
        accept="image/*"
        onFiles={handleFiles}
        formats="PNG • JPG • SVG • WEBP"
        label="Drag & drop your logo or image here"
        sublabel="or click to upload"
      />

      {previews.length > 0 && (
        <>
          <div className="grid grid-cols-5 gap-3">
            {previews.map(p => (
              <button
                key={p.size}
                onClick={() => downloadSingle(p)}
                className="flex flex-col items-center gap-2 rounded-xl border border-border bg-card p-3 shadow-soft hover:shadow-card transition-all group"
              >
                <div className="flex items-center justify-center h-16 w-16">
                  <img
                    src={p.dataUrl}
                    alt={`${p.size}x${p.size}`}
                    style={{ width: Math.max(p.size, 16), height: Math.max(p.size, 16), maxWidth: 64, maxHeight: 64 }}
                    className="rounded border border-border"
                  />
                </div>
                <span className="text-xs font-medium text-muted-foreground group-hover:text-primary transition-colors">
                  {p.size}×{p.size}
                </span>
              </button>
            ))}
          </div>

          <Button onClick={downloadAll} className="w-full h-11 rounded-xl gap-2">
            <Download className="h-4 w-4" /> Download All as ZIP
          </Button>

          <Button
            variant="ghost"
            size="sm"
            className="w-full text-muted-foreground"
            onClick={() => { setPreviews([]); setSourceFile(null); }}
          >
            Upload a different image
          </Button>
        </>
      )}
    </div>
  );
};

export default FaviconGeneratorTool;
